baseURL = 'https://harshfolio.github.io/portfolio/'
languageCode = 'en-us'
title = 'Harsh Sharma'
theme = 'PaperMod'

[params]
  description = "Personal blog and portfolio"
  author = "Harsh Sharma"

  # Clean, minimal theme settings
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

  # Math/LaTeX support
  math = true

[params.homeInfoParams]
  Title = "Harsh Sharma"
  Content = "Personal blog and portfolio"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/harshfolio"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
