baseURL = 'https://harshfolio.github.io/portfolio/'
languageCode = 'en-us'
title = 'Harsh Sharma'
theme = 'PaperMod'

[params]
  description = "Personal blog and portfolio"
  author = "Harsh Sharma"

  # eugeneyan.com inspired settings
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false

  # Math/LaTeX support
  math = true

[params.homeInfoParams]
  Title = "Hi, I'm Harsh Sharma"
  Content = "Welcome to my personal blog where I write about analytics, data, and technology."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/harshfolio/"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/harshxharsh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
