baseURL = 'https://harshfolio.github.io/portfolio/'
languageCode = 'en-us'
title = 'Harsh Sharma'
theme = 'PaperMod'

[params]
  description = "Personal blog and portfolio"
  author = "Harsh Sharma"

  # eugeneyan.com inspired settings
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false

  # Math/LaTeX support
  math = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/harshfolio/"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/harshxharsh"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/Harshxharsh"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "monokai"
