baseURL = 'https://harshfolio.github.io/'
languageCode = 'en-us'
title = 'Harsh Sharma'
theme = 'PaperMod'
enableRobotsTXT = true

# Build configuration for optimization
[build]
  writeStats = true

[build.buildStats]
  enable = true

# Minification settings
[minify]
  minifyOutput = true
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false

[params]
  description = "Personal blog and portfolio"
  author = "Harsh Sharma"
  # Sections to list on home page
  mainSections = ["posts"]

  # Site icon/favicon
  assets.favicon = "/images/harsh-sharma.jpeg"
  assets.favicon16x16 = "/images/harsh-sharma.jpeg"
  assets.favicon32x32 = "/images/harsh-sharma.jpeg"
  assets.apple_touch_icon = "/images/harsh-sharma.jpeg"

  # eugeneyan.com inspired settings
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false

  # Math/LaTeX support
  math = true

# Primary navigation (Hugo Menus)
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/harshfolio/"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/harshxharsh"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/Harshxharsh"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "monokai"
